### ISSUE TITLE
[BUG]: <Provide a clear, descriptive title>

### ISSUE THREAD

**Issue by mrtknrt** [AIHawk-co/Auto_Jobs_Applier_AI_Agent#836] opened 2024-11-13 10:36 UTC
### Steps to reproduce

program is just scrolling scrolling then jump to other job application and scroll that too, and then jump to another one, and do not apply any of these jobs, what is wrong with the program?

### Branch

None

**Comment by Tgenz1213** [comment] 2024-11-13 14:12
Review the logs. If the model you're using is rating your eligibility below 7, it won't apply. Is it skipping jobs that have a rating of 7 and up?

**Comment by surapuramakhil** [comment] 2024-11-13 16:26
@mrtknrt we can't say unless you add any logs, as @Tgenz1213 reviewing logs is the best option to know why.

**Comment by surapuramakhil** [comment] 2024-11-13 20:28
> > Review the logs. If the model you're using is rating your eligibility below 7, it won't apply. Is it skipping jobs that have a rating of 7 and up?
> 
> oh wow, this program is smarter than I thought, how can I reduce this rating number from 7 to 1? thanks

don't do that, it will harm you more than benefit you. it's there for a reason. refine you plain text resume, add as much information about you - skills, projects, experience.

closing this as it is not a bug.

**Closed by surapuramakhil** 2024-11-13 20:28 UTC
Labels: bug, needs more info
